"""Per-section code references for the report.

Line numbers are resolved from the source by symbol name (via ast), so they stay correct when
code moves. Emits report/codelinks.tex:

    \\newcommand{\\codeIntro}{\\CodeRef{hm_fig4c/data.py}{97}{188}{build\\_tables}...}

\\CodeRef renders as a hyperlink when \\repourl is set in the .tex preamble, and as a plain
file:line reference otherwise (this VM cannot create the GitHub remote -- the exe.dev proxy
serves only /repos/OWNER/REPO -- so the fallback is the default).

    uv run python report/codelinks.py
"""
from __future__ import annotations

import ast
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "report" / "codelinks.tex"

# section macro -> [(module, symbol or None for whole file)]
SECTIONS: dict[str, list[tuple[str, str | None]]] = {
    "codeApproach": [("hm_fig4c/data.py", "build_tables"), ("hm_fig4c/data.py", "prepare"),
                     ("hm_fig4c/preprocess.py", "preregistered_launches"),
                     ("hm_fig4c/preprocess.py", "filter_by_number_of_groups_of_min_size")],
    "codeMinority": [("hm_fig4c/analysis.py", "assign_minority"),
                     ("hm_fig4c/pipeline.py", "select_cohort")],
    "codeAgreement": [("hm_fig4c/data.py", "endpoint_texts"),
                      ("hm_fig4c/analysis.py", "position_axis_scores"),
                      ("hm_fig4c/analysis.py", "score_texts"), ("hm_fig4c/embed.py", "run")],
    "codeAgreementValidation": [("hm_fig4c/pipeline.py", "fig4a_correlation"),
                                ("report/compute_values.py", "marginal_r2")],
    "codeRepresentation": [("hm_fig4c/analysis.py", "convex_lstsq"),
                           ("hm_fig4c/analysis.py", "convex_fit_with_se"),
                           ("hm_fig4c/analysis.py", "build_design"),
                           ("hm_fig4c/analysis.py", "minority_weight")],
    "codeSanity": [("hm_fig4c/analysis.py", "opinion_self_regression")],
    "codeResults": [("hm_fig4c/pipeline.py", "run_minority_analysis"),
                    ("hm_fig4c/analysis.py", "cluster_bootstrap"),
                    ("report/figures.py", None)],
    "codeSensitivity": [("notebooks/make_notebook.py", None),
                        ("report/compute_values.py", "sensitivity_summary")],
    "codeValidationExtra": [("hm_fig4c/pipeline.py", "fig4b_within_range")],
}


def spans(module: str) -> dict[str, tuple[int, int]]:
    src = (ROOT / module).read_text()
    tree = ast.parse(src)
    out: dict[str, tuple[int, int]] = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            out[node.name] = (node.lineno, node.end_lineno or node.lineno)
    out["__file__"] = (1, len(src.splitlines()))
    return out


def main() -> None:
    try:
        commit = subprocess.check_output(["git", "-C", str(ROOT), "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        commit = ""

    cache: dict[str, dict[str, tuple[int, int]]] = {}
    lines = ["% GENERATED by report/codelinks.py -- do not edit.",
             f"\\newcommand{{\\repocommit}}{{{commit[:9]}}}",
             f"\\newcommand{{\\repocommitfull}}{{{commit}}}", ""]
    index: dict[str, list] = {}
    for macro, refs in SECTIONS.items():
        parts = []
        for module, symbol in refs:
            cache.setdefault(module, spans(module))
            key = symbol or "__file__"
            if key not in cache[module]:
                raise SystemExit(f"{module}: no symbol {symbol}")
            a, b = cache[module][key]
            label = (symbol + "()").replace("_", r"\_") if symbol else "(whole file)"
            # raw path for the URL, TeX-escaped path for display
            parts.append(f"\\CodeRef{{{module}}}{{{module.replace('_', r'\_')}}}{{{a}}}{{{b}}}{{{label}}}")
            index.setdefault(macro, []).append({"module": module, "symbol": symbol, "start": a, "end": b})
        lines.append(f"\\newcommand{{\\{macro}}}{{{' '.join(parts)}}}")
    OUT.write_text("\n".join(lines) + "\n")
    (ROOT / "report" / "codelinks.json").write_text(json.dumps(index, indent=1))
    print(f"wrote {OUT} ({len(SECTIONS)} section macros, commit {commit[:9] or 'n/a'})")


if __name__ == "__main__":
    main()
