[project]
name = "habermas-fig4c"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Max Davy", email = "max.davy98@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "nbconvert>=7.17.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "scipy>=1.18.1",
    "sentence-transformers>=3",
    "statsmodels>=0.15.0",
    "torch>=2.14.0",
]

[project.scripts]
habermas-fig4c = "habermas_fig4c:main"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cpu"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
